# -*- coding: utf-8 -*-
"""Damin_KMeansClustering_1301164074.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O_v4yxO47NCg4NUpIuhuZPvQsXObWmik

**KMeans Clustering**
"""

#masukan library
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs

#mengeluarkan dataset
dataset = make_blobs(n_samples=300, 
                     centers=4, 
                     n_features=2, 
                     cluster_std=1.6, 
                     random_state=50)

points = dataset[0]

#masukan kmeans
from sklearn.cluster import KMeans

#membuat objek Kmeas
kmeans = KMeans(n_clusters=4)

#menyesuaikan objek kmeans dengan dataset
kmeans.fit(points)

plt.scatter(dataset[0][:,0], dataset[0][:,1])

clusters = kmeans.cluster_centers_

#menampilkan cluster
print(clusters)

y_km = kmeans.fit_predict(points)

plt.scatter(points[y_km == 0,0], points[y_km == 0,1], s=50, color = 'red')
plt.scatter(points[y_km == 1,0], points[y_km == 1,1], s=50, color = 'yellow')
plt.scatter(points[y_km == 2,0], points[y_km == 2,1], s=50, color = 'gray')
plt.scatter(points[y_km == 3,0], points[y_km == 3,1], s=50, color = 'green')

plt.scatter(clusters[0][0], clusters[0][1], marker = '*', s = 220, color = 'black')
plt.scatter(clusters[1][0], clusters[1][1], marker = '*', s = 220, color = 'black')
plt.scatter(clusters[2][0], clusters[2][1], marker = '*', s = 220, color = 'black')
plt.scatter(clusters[3][0], clusters[3][1], marker = '*', s = 220, color = 'black')

plt.show()



